# -*- coding: utf-8 -*-


# Form implementation generated from reading ui file 'smtp.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog, QMessageBox


BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, BASE_DIR)

from smtp.SmtpUtil import Smtp
from utils import StringUtils

class Ui_MainWindow(object):


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(583, 481)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../res/smtpIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
    
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout.addWidget(self.plainTextEdit)
        self.verticalLayout_6.addLayout(self.verticalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setAutoRepeat(False)
        self.pushButton_2.setAutoRepeatDelay(200)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_3.addLayout(self.horizontalLayout_4)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 583, 18))
        self.menubar.setObjectName("menubar")

        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        #点击动作事件触发
        self.pushButton.clicked.connect(self.addFile)
        self.pushButton_2.clicked.connect(self.send)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "smtp邮件发送"))
        self.label.setText(_translate("MainWindow", "收件人地址："))
        self.label_2.setText(_translate("MainWindow", "邮件主题："))
        self.label_3.setText(_translate("MainWindow", "内容："))
        self.plainTextEdit.setPlainText(_translate("MainWindow", "..."))
        self.pushButton.setText(_translate("MainWindow", "添加文件"))
        self.pushButton_2.setText(_translate("MainWindow", "确认发送"))
        self.fileName = ''

    def send(self):

        receiver=self.lineEdit.text()
        title=self.lineEdit_2.text()
        content=self.plainTextEdit.toPlainText()
        print(receiver+""+title+" "+content)
        if StringUtils.isNull(receiver) or StringUtils.isNull(title):
            QMessageBox.information(self.MainWindow, '警告', '邮件接收者和邮件主题不能为空!',
                                    QMessageBox.Ok | QMessageBox.Close,
                                    QMessageBox.Close)
        smtp = Smtp()
        smtp.loginSmtp()
        if StringUtils.isNull(self.fileName):
            smtp.sendMessage(content,title,receiver)
        else:
            smtp.sendMsgAndFile(content,title,self.filePath,self.fileName,receiver)

    def addFile(self):
        file=QFileDialog.getOpenFileName()
        self.filePath=file[0]
        self.fileName=os.path.basename(self.filePath)
        self.plainTextEdit.appendPlainText("附件:"+self.filePath)
        print(self.filePath)
        print(self.fileName)



if __name__=='__main__':
    import sys

    app = QtWidgets.QApplication(sys.argv)
    widget = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(widget)
    widget.show()
    sys.exit(app.exec_())